<?php

namespace ProjBundle\Repository;

/**
 * CoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllTri()
    {
        try {
            return $this->getEntityManager()
                ->createQuery(
                    "SELECT p
                FROM ProjBundle:Cours
                p ORDER BY p.dateDebut ASC"
                )
                ->getResult();
        } catch (NonUniqueResultException $e) {

        }
    }

    public function findAllTri2()
    {
        try {
            return $this->getEntityManager()
                ->createQuery(
                    "SELECT p
                FROM ProjBundle:Cours
                p ORDER BY p.dateFin ASC"
                )
                ->getResult();
        } catch (NonUniqueResultException $e) {

        }
    }

    public function search($c)
    {
        try {
            return $this->getEntityManager()
                ->createQuery(
                    "SELECT p
                FROM ProjBundle:Cours
                p where p.nomCours = :c"
                )
                ->setParameter("c",$c)
                ->getResult();
        } catch (NonUniqueResultException $e) {

        }
    }
}
