<?php

namespace ProjBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllTri()
    {
        try {
            return $this->getEntityManager()
                ->createQuery(
                    "SELECT p
                FROM ProjBundle:Reservation
                p ORDER BY p.datereservation Desc"
                )
                ->getResult();
        } catch (NonUniqueResultException $e) {

        }
    }


}
